# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-09 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_pagebanner_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='info',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birday',
            field=models.DateField(blank=True, null=True, verbose_name='\u751f\u65e5'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='\u5973', max_length=6, verbose_name='\u6027\u522b'),
        ),
    ]
