# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-09 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180209_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Userlog',
        ),
    ]
