# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-10 22:29
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='\u6807\u9898')),
                ('image', models.ImageField(upload_to='movies/%Y/%m', verbose_name='\u5c01\u9762\u56fe')),
                ('movie_tag', models.CharField(default='\u5267\u60c5', max_length=10, verbose_name='\u6807\u7b7e')),
                ('star', models.CharField(default='xxx', max_length=5, verbose_name='\u661f\u7ea7')),
                ('play_nums', models.IntegerField(default=0, verbose_name='\u64ad\u653e\u91cf')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u4eba\u6570')),
                ('comment_nums', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u91cf')),
                ('url', models.CharField(default='', max_length=200, verbose_name='\u8bbf\u95ee\u5730\u5740')),
                ('video_times', models.CharField(max_length=30, verbose_name='\u89c6\u9891\u65f6\u957f(\u5206\u949f\u6570)')),
                ('area', models.CharField(max_length=20, verbose_name='\u4e0a\u6620\u5730\u533a')),
                ('release_time', models.DateField(verbose_name='\u4e0a\u6620\u65f6\u95f4')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='\u5f71\u7247\u4ecb\u7ecd')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7535\u5f71\u4fe1\u606f',
                'verbose_name_plural': '\u7535\u5f71\u4fe1\u606f',
            },
        ),
    ]
