# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-10 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180210_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_tag',
            field=models.CharField(default='\u5267\u60c5', max_length=10, verbose_name='\u6807\u7b7e'),
        ),
    ]
