# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-10 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20180210_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_tag',
            field=models.CharField(choices=[('jq', '\u5267\u60c5'), ('aq', '\u7231\u60c5'), ('qh', '\u5947\u5e7b')], default='\u5267\u60c5', max_length=10, verbose_name='\u6807\u7b7e'),
        ),
    ]
